### ISSUE TITLE
`Zarkov.literal` simplification

### ISSUE THREAD

**Issue by AlexChadwickP** [MarquisdeGeek/Zarkov#1]
Hi Steven,

Any reason why you decided to duplicate the code used for the `const` function as opposed to just setting `Zarkov.literal = Zarkov.const`? I may be missing something obvious here!

```diff
- Zarkov.literal = function(value) { // This is intentionally identical to const (true in typeless langs only)
-   return {
-     redo: function(/*state not needed for (string) literal*/) { return value; },
-   }
- }
+ Zarkov.literal = Zarkov.const // This is intentionally identical to const (true in typeless langs only)
```

**Comment by MarquisdeGeek** [comment]
It's easier (for me) to stick a breakpoint in the specific named function, when I need to determine which version was called.
